//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront2.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStatus
    {
        public int PSID { get; set; }
        public int ProductID { get; set; }
        public int LocationID { get; set; }
        public short InStock { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Discontinued { get; set; }
        public string Section { get; set; }
        public short Col { get; set; }
        public short Row { get; set; }
    
        public virtual Locations Location { get; set; }
        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}
